### ISSUE TITLE
对background-size的建议

### ISSUE THREAD

**Issue by xgszl33614** [linxz/blog#1]
我觉得这样说可能更容易理解：
background-size：contain。图片根据自身比例缩放，至某边等于应用容器的相应边size。
background-size：cover。图片根据自身比例缩放，至某边等于应用容器的相应边size，且另一边也大于            等于应用容器的相应边的size。
另外：background-size与background分开写时，background-size必须在background后面才生效

**Comment by linxz** [comment]
@xgszl33614 
`contain`和`cover`都是**自身比例缩放**，当时我觉得这个或许也可以叫**等比缩放**，不过后面的部分按照你所说的，我觉得似乎更容易让人能够理解。赞一个，看来以后在文字表达上还是需要再努力提高。

另外`background-size`如果是`background`中的一部分了，那么分开写的时候，必然是要写在`background`后面啊，毕竟`background`是复合属性，包含了各种**background**。

**Comment by xgszl33614** [comment]
嗯，对，会覆盖。重点不是自身比例缩放，而是后面那句。你说的contain以最大的比例填充，cover以最小的比例填充，对于要学习这个属性的人无法理解，直观感觉会是这样：contain将图片放大的比例比cover大，但实际上是反过来的。
噢，我没注意，你是说后面有点难理解。那就OK了。

**Comment by linxz** [comment]
@xgszl33614 我已经被绕晕了……不过读了几次自己写的那个什么**最大**和**最小**，的确似乎是容易被人误解……借用水群_Evan_的话……

> 我觉得cover就是把背景图缩放到刚好能覆盖整个元素
> 而contain就是缩放到刚好可以在元素内部显示整个background-image
> 大概是这样吧

**Comment by xgszl33614** [comment]
嗯，是这样

**Comment by Wowhoo** [comment]
对cover 和contain 2个值：
cover(图片的短边变化到容器相应边的100% 图片的长边变化则auto)；
contain(图片的长边变化到容器相应边的100% 图片的短边变化则auto)；

（这其中auto的变化是保持图片的原始宽高比不变的）上边2者的值域为（100% auto 或者auto 100%）中的一个，且2者不相同（只有当容器宽高比和图片宽高比一致时才相同）

**Comment by riskers** [comment]
@xgszl33614 我觉得 `contain` 和 `cover` 效果如何完全要看背景图和容器的宽高比来决定。

详见这篇[文章](https://github.com/riskers/blog/issues/10)
