### ISSUE TITLE
进阶CSS从零开始突破 3.4.2 层叠优先级顺序有误

### ISSUE THREAD

**Issue by fighterleslie** [linxz/blog#2]
您在文章（进阶CSS从零开始突破）中提到的优先级顺序有误，文中的顺序（按优先级升序）：

```
1. user agent stylesheet
2. author style sheets
3. user style sheets
4. author style sheets !important
5. user style sheets !important
```

实际的顺序：

```
1. user agent declarations
2. user declarations
3. author declarations
4. author declarations with !important
5. user declarations with !important
```

参考：[CSS Spec Section 6.4.1](http://www.w3.org/TR/CSS21/cascade.html#cascading-order)
这种处理是对 `user` 和 `author` 权限的平衡，一般情况下author 的权重高于 user，这是对 `author` 创作的尊重；但对于特殊用户（例如：色盲、色弱、近视用户），他们具有特殊需求（例如 大字号、特定的颜色对比），这种需求可以通过 user !important 声明来获得最高优先级。

**Comment by linxz** [comment]
感谢，已经更新。
